- project:
    check:
      fail-fast: true
      jobs:
        - clang-format:
            voting: false
        - f29-gcc-cover:
            requires: CzechLight-deps-f29-gcc
            provides: coverage-f29-gcc
        - f29-gcc-cover-diff:
            voting: false
            requires:
              - CzechLight-deps-f29-gcc
              - coverage-f29-gcc
            dependencies:
              - f29-gcc-cover
        - f29-gcc-asan-ubsan:
            requires: CzechLight-deps-f29-gcc-asan-ubsan
        - f29-clang-asan:
            requires: CzechLight-deps-f29-clang-asan
        - f29-clang-tsan:
            requires: CzechLight-deps-f29-clang-tsan
