- project:
    check:
      jobs:
        - f32-gcc-cover:
            requires: CzechLight-deps-f32-gcc
        - f32-clang-asan-ubsan:
            requires: CzechLight-deps-f32-clang-asan-ubsan
        - f32-clang-tsan:
            requires: CzechLight-deps-f32-clang-tsan
        - f32-cpp-coverage-diff:
            voting: false
        - clang-format:
            voting: false
        - f32-gcc-cover-previous:
            requires: CzechLight-deps-f32-gcc
