- job:
    name: f38-gcc-netconf-cli-no-sysrepo
    description: |
      Build a minimal version without sysrepo or the test suite
    parent: f38-gcc

- job:
    name: netconf-cli-f38-clang-asan-ubsan
    parent: f38-clang-asan-ubsan
    pre-run: ci/pre.yaml
    requires: CzechLight-deps-f38-clang-asan-ubsan
    timeout: 1800
    vars:
      zuul_work_dir: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/netconf-cli'].src_dir }}"

- project:
    check:
      jobs:
        - f38-gcc-cover:
            pre-run: ci/pre.yaml
            requires: CzechLight-deps-f38-gcc
            required-projects: &projects
              - CzechLight/dependencies
            timeout: 1800
        - netconf-cli-f38-clang-asan-ubsan:
            required-projects: *projects
        - f38-clang-tsan:
            pre-run: ci/pre.yaml
            requires: CzechLight-deps-f38-clang-tsan
            required-projects: *projects
            timeout: 1800
        - f38-gcc-netconf-cli-no-sysrepo:
            pre-run: ci/pre.yaml
            requires: CzechLight-deps-f38-gcc
            required-projects: *projects
            timeout: 1800
        - f38-cpp-coverage-diff:
            pre-run: ci/pre.yaml
            voting: false
            timeout: 1800
        - clang-format:
            voting: false
        - f38-gcc-cover-previous:
            pre-run: ci/pre.yaml
            requires: CzechLight-deps-f38-gcc
            required-projects: *projects
            timeout: 1800
        - czechlight-clearfog:
            required-projects:
              - CzechLight/br2-external
            requires: CzechLight-br2-build-clearfog
            timeout: 1800
