- job:
    name: f34-gcc-netconf-cli-no-sysrepo
    description: |
      Build a minimal version without sysrepo or the test suite
    parent: f34-gcc

- job:
    name: netconf-cli-f34-gcc-cover
    parent: f34-gcc-cover
    pre-run: ci/pre.yaml
    requires: CzechLight-deps-f34-gcc
    required-projects: &projects
      - CzechLight/dependencies
    vars: &z_proj_vars
      zuul_work_dir: "{{ zuul.projects[zuul.project.canonical_hostname + '/CzechLight/netconf-cli'].src_dir }}"

- job:
    name: netconf-cli-f34-clang-asan-ubsan
    pre-run: ci/pre.yaml
    requires: CzechLight-deps-f34-clang-asan-ubsan
    required-projects: *projects
    vars: *z_proj_vars

- job:
    name: netconf-cli-f34-clang-tsan
    pre-run: ci/pre.yaml
    requires: CzechLight-deps-f34-clang-tsan
    required-projects: *projects
    vars: *z_proj_vars

- project:
    check:
      jobs:
        - netconf-cli-f34-gcc-cover
        - netconf-cli-f34-clang-asan-ubsan
        - netconf-cli-f34-clang-tsan
        - f34-gcc-netconf-cli-no-sysrepo:
            pre-run: ci/pre.yaml
            requires: CzechLight-deps-f34-gcc
            required-projects: *projects
        - f34-cpp-coverage-diff:
            pre-run: ci/pre.yaml
            voting: false
        - clang-format:
            voting: false
        - f34-gcc-cover-previous:
            pre-run: ci/pre.yaml
            requires: CzechLight-deps-f34-gcc
            required-projects: *projects
        - czechlight-clearfog:
            required-projects:
              - CzechLight/br2-external
            requires: CzechLight-br2-build-clearfog
