- job:
    name: f33-gcc-netconf-cli-no-sysrepo
    description: |
      Build a minimal version without sysrepo or the test suite
    parent: f33-gcc

- project:
    check:
      jobs:
        - f33-gcc-cover:
            requires: CzechLight-deps-f33-gcc
        - f33-clang-asan-ubsan:
            requires: CzechLight-deps-f33-clang-asan-ubsan
        - f33-clang-tsan:
            requires: CzechLight-deps-f33-clang-tsan
        - f33-gcc-netconf-cli-no-sysrepo:
            requires: CzechLight-deps-f33-gcc
        - f33-cpp-coverage-diff:
            voting: false
        - clang-format:
            voting: false
        - f33-gcc-cover-previous:
            requires: CzechLight-deps-f33-gcc
