- project:
    check:
      fail-fast: true
      jobs:
        - f29-gcc-cover:
            requires: CzechLight-deps-f29-gcc
            provides: coverage-f29-gcc
        - f29-gcc-cover-diff:
            voting: false
            requires:
              - CzechLight-deps-f29-gcc
              - coverage-f29-gcc
            dependencies:
              - f29-gcc-cover
