- hosts: all
  tasks:
    - name: install pcre2
      package:
        name: pcre2-devel
        state: present
      become: true

    - name: install PAM
      package:
        name: pam-devel
        state: present
      become: true
