- hosts: all
  tasks:
    - name: install deps
      package:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - pcre2-devel
        - xxhash-devel
        - libcurl-devel
        - openssl-perl
        - pam-devel
        - docopt-cpp-devel
